exec-once = kitty
exec-once = hyprpaper
exec-once = waybar
exec-once = discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy --start-minimized

#xwayland
exec-once = systemctl --user import-environment WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE

#hyprland signature
exec-once = sleep 2; export HYPRLAND_INSTANCE_SIGNATURE=$(ls -t /run/user/$(id -u)/hypr/ | head -n1) export HYPRLAND_INSTANCE_SIGNATURE

#swayidle inactivity suspend
exec-once = swayidle -w timeout 900 "systemctl suspend"

#polkit agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1   
