# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


xwayland {
    force_zero_scaling = true
}   

layerrule {
	name = blur_wofi
	match:namespace = wofi
	blur = true
	ignore_alpha=0.01
}

layerrule {
	name = notif_blur
	match:namespace = notifications
	blur = true
	ignore_alpha=0.01
}

layerrule {
    name = wofi_slide
    match:namespace = wofi
    animation =  slide
}

layerrule {
	name = waybar_slide
	match:namespace = waybar
	animation = slide top
}

layerrule {
    name = slurp_slide
    match:namespace = selection
    animation = fade
}

animation = layersIn, 1, 5, easeOutQuint, slide
animation = layersOut, 1, 100, default, slide
